#!/bin/bash
set -e

COMMIT="$1"
LOGFILE="$2"

SAFE_COMMIT=$(echo "$COMMIT" | tr -c '[a-zA-Z0-9]' '-')

export BLINK_CAPTURE=1 # Capture screenshots

cd visual/timecounts-frontend
git fetch >>"$LOGFILE" 2>/dev/null || (echo "Git fetch failed" && exit 1)
git reset --hard "$COMMIT" >>"$LOGFILE" 2>/dev/null || (echo "Git reset failed" && exit 2)
git clean -f >>"$LOGFILE" 2>/dev/null || (echo "Git clean failed" && exit 3)
rm -Rf build >>"$LOGFILE" 2>/dev/null || (echo "Delete build folder failed" && exit 4)
npm install >>"$LOGFILE" 2>/dev/null || (echo "npm install failed" && exit 5)
./install-api.sh >>"$LOGFILE" 2>/dev/null || (echo "install-api failed" && exit 6)
TEST_STATUS=0
./test.sh >>"$LOGFILE" 2>/dev/null || TEST_STATUS=$?
if [ "$TEST_STATUS" -gt "0" ]; then
  echo "Test failed for $COMMIT";
  echo '```'
  tail -n 30 $LOGFILE
  echo '```'
  exit 1;
fi
cd ../..
mkdir -p "archive/$SAFE_COMMIT/"
cp -r visual/timecounts-frontend/screenshots/* archive/$SAFE_COMMIT
exit 0
