#!/bin/bash
set -e
cd "$(dirname $0)"
BRANCH_NAME="$1"
BASE_COMMIT="$2"
HEAD_COMMIT="$3"
export CIRCLE_BRANCH="$BRANCH_NAME"
LOGFILE="$(pwd)/logs/$(echo -n "${BASE_COMMIT}-${HEAD_COMMIT}" | tr -c "[a-zA-Z0-9]" "-").txt"
echo "STARTING NEW BUILD: $(date)" >> $LOGFILE
rm -Rf "archive/${BASE_COMMIT}"
rm -Rf "archive/${HEAD_COMMIT}"
if [ ! -d "archive/${BASE_COMMIT}" ]; then
  ./visbuild $BASE_COMMIT $LOGFILE
fi
if [ ! -d "archive/${HEAD_COMMIT}" ]; then
  ./visbuild $HEAD_COMMIT $LOGFILE
fi
